<?php

// DO NOT EDIT THIS FILE
// THE GAME DEPENDS ON THESE VALUES

/*

	U                     |                     U
	  Y                   |                   K
		+---+-----------+---+-----------+---+
		| Q |   L 0 6   | N |   L 0 7   | Q |
		+---/---+---+---\---/---+---+---\---+
		|   | 8 | 6 | 3 |   | 5 | 7 | 8 |   |
		| L +---+---+---+ L |---+---+---+ L |
		| 0 | 7 | 4 | 1 | 0 | 2 | 4 | 6 | 0 |
		| 5 +---+---+---+ 1 |---+---+---+ 8 |
		|   | 5 | 2 | 0 |   | 0 | 1 | 3 |   |
		+---\---+---+---/---\---+---+---/---+
	----| W |   L 0 4   | X |   L 0 2   | E |----
		+---/---+---+---\---/---+---+---\---+
		|   | 3 | 1 | 0 |   | 0 | 2 | 5 |   |
		| L +---+---+---+ L |---+---+---+ L |
		| 1 | 6 | 4 | 2 | 0 | 1 | 4 | 7 | 0 |
		| 2 +---+---+---+ 3 |---+---+---+ 9 |
		|   | 8 | 7 | 5 |   | 3 | 6 | 8 |   |
		+---\---+---+---/---\---+---+---/---+
		| Q |   L 1 1   | S |   L 1 0   | Q |
		+---+-----------+---+-----------+---+
	  R                   |                   A
	U                     |                     U

*/

// generate an array of sectors for the various board arrays
// white space added for easier visualization
$SECTORS = array(
	'YU',                                                     'KU',

		'YQ',        'L06',      'N',         'L07',      'KQ',

			   'Y8', 'Y6', 'Y3',        'K5', 'K7', 'K8',

		'L05', 'Y7', 'Y4', 'Y1', 'L01', 'K2', 'K4', 'K6', 'L08',

			   'Y5', 'Y2', 'Y0',        'K0', 'K1', 'K3',

		 'W',        'L04',       'X',        'L02',       'E',

			   'R3', 'R1', 'R0',        'A0', 'A2', 'A5',

		'L12', 'R6', 'R4', 'R2', 'L03', 'A1', 'A4', 'A7', 'L09',

			   'R8', 'R7', 'R5',        'A3', 'A6', 'A8',

		'RQ',        'L11',       'S',        'L10',      'AQ',

	'RU',                                                     'AU'
);

// generate the adjacencies
// RESERVE -> HEADQUARTERS (*U -> *Q) IS ONLY ONE WAY
$LAND = array(
	'YU'  => 'YQ',
	'KU'  => 'KQ',

	'YQ'  => 'Y8',
	'N'   => 'Y3,K5',
	'KQ'  => 'K8',

	'Y8'  => 'YQ,Y6,Y7,Y4',
	'Y6'  => 'Y8,Y3,Y7,Y4,Y1',
	'Y3'  => 'N,Y6,Y4,Y1',
	'K5'  => 'N,K7,K2,K4',
	'K7'  => 'K5,K8,K2,K4,K6',
	'K8'  => 'KQ,K7,K4,K6',

	'Y7'  => 'Y8,Y6,Y4,Y5,Y2',
	'Y4'  => 'Y8,Y6,Y3,Y7,Y1,Y5,Y2,Y0',
	'Y1'  => 'Y6,Y3,Y4,Y2,Y0',
	'K2'  => 'K5,K7,K4,K0,K1',
	'K4'  => 'K5,K7,K8,K2,K6,K0,K1,K3',
	'K6'  => 'K7,K8,K4,K1,K3',

	'Y5'  => 'Y7,Y4,Y2,W',
	'Y2'  => 'Y7,Y4,Y1,Y5,Y0',
	'Y0'  => 'Y4,Y1,Y2,X',
	'K0'  => 'K2,K4,K1,X',
	'K1'  => 'K2,K4,K6,K0,K3',
	'K3'  => 'K4,K6,K1,E',

	'W'   => 'Y5,R3',
	'X'   => 'Y0,K0,R0,A0',
	'E'   => 'K3,A5',

	'R3'  => 'W,R1,R6,R4',
	'R1'  => 'R3,R0,R6,R4,R2',
	'R0'  => 'X,R1,R4,R2',
	'A0'  => 'X,A2,A1,A4',
	'A2'  => 'A0,A5,A1,A4,A7',
	'A5'  => 'E,A2,A4,A7',

	'R6'  => 'R3,R1,R4,R8,R7',
	'R4'  => 'R3,R1,R0,R6,R2,R8,R7,R5',
	'R2'  => 'R1,R0,R4,R7,R5',
	'A1'  => 'A0,A2,A4,A3,A6',
	'A4'  => 'A0,A2,A5,A1,A7,A3,A6,A8',
	'A7'  => 'A2,A5,A4,A6,A8',

	'R8'  => 'R6,R4,R7,RQ',
	'R7'  => 'R6,R4,R2,R8,R5',
	'R5'  => 'R4,R2,R7,S',
	'A3'  => 'A1,A4,A6,S',
	'A6'  => 'A1,A4,A7,A3,A8',
	'A8'  => 'A4,A7,A6,AQ',

	'RQ'  => 'R8',
	'S'   => 'R5,A3',
	'AQ'  => 'A8',

	'RU'  => 'RQ',
	'AU'  => 'AQ'
);

$SEA = array(
	'YU'  => 'YQ',
	'KU'  => 'KQ',

	'YQ'  => 'L06,L05,Y8',
	'L06' => 'YQ,N,Y8,Y6,Y3',
	'N'   => 'L06,L07,Y3,L01,K5',
	'L07' => 'N,KQ,K5,K7,K8',
	'KQ'  => 'L07,K8,L08',

	'Y8'  => 'YQ,L06,L05,Y6,Y7',
	'Y6'  => 'L06,Y8,Y3',
	'Y3'  => 'L06,N,Y6,L01,Y1',
	'K5'  => 'N,L07,L01,K7,K2',
	'K7'  => 'L07,K5,K8',
	'K8'  => 'L07,KQ,K7,L08,K6',

	'L05' => 'YQ,Y8,Y7,Y5,W',
	'Y7'  => 'L05,Y8,Y5',
	'Y1'  => 'Y3,L01,Y0',
	'L01' => 'N,Y3,K5,Y1,K2,Y0,K0,X',
	'K2'  => 'L01,K5,K0',
	'K6'  => 'K8,L08,K3',
	'L08' => 'KQ,K8,K6,K3,E',

	'Y5'  => 'L05,Y7,Y2,W,L04',
	'Y2'  => 'Y5,Y0,L04',
	'Y0'  => 'Y1,L01,Y2,L04,X',
	'K0'  => 'L01,K2,K1,X,L02',
	'K1'  => 'K0,K3,L02',
	'K3'  => 'K6,L08,K1,L02,E',

	'W'   => 'L05,Y5,L04,L12,R3',
	'L04' => 'Y5,Y2,Y0,W,X,R3,R1,R0',
	'X'   => 'Y0,L01,K0,L04,L02,R0,L03,A0',
	'L02' => 'K0,K1,K3,X,E,A0,A2,A5',
	'E'   => 'K3,L08,L02,A5,L09',

	'R3'  => 'W,L04,L12,R1,R6',
	'R1'  => 'L04,R3,R0',
	'R0'  => 'L04,X,R1,L03,R2',
	'A0'  => 'X,L02,L03,A2,A1',
	'A2'  => 'L02,A0,A5',
	'A5'  => 'L02,E,A2,L09,A7',

	'L12' => 'W,R3,R6,R8,RQ',
	'R6'  => 'L12,R3,R8',
	'R2'  => 'R0,L03,R5',
	'L03' => 'X,R0,A0,R2,A1,R5,A3,S',
	'A1'  => 'L03,A0,A3',
	'A7'  => 'A5,L09,A8',
	'L09' => 'E,A5,A7,A8,AQ',

	'R8'  => 'L12,R6,R7,RQ,L11',
	'R7'  => 'R8,R5,L11',
	'R5'  => 'R2,L03,R7,L11,S',
	'A3'  => 'L03,A1,A6,S,L10',
	'A6'  => 'A3,A8,L10',
	'A8'  => 'A7,L09,A6,L10,AQ',

	'RQ'  => 'L12,R8,L11',
	'L11' => 'R8,R7,R5,RQ,S',
	'S'   => 'R5,L03,A3,L11,L10',
	'L10' => 'A3,A6,A8,S,AQ',
	'AQ'  => 'A8,L09,L10',

	'RU'  => 'RQ',
	'AU'  => 'AQ'
);


// generate the piece array
$PIECE = array(
	'I' => array(
		'name'        => 'Infantry',
		'method'      => 'LAND',
		'power'       => '2',
		'max_sectors' => '2',
		'size'        => 'small',
		'exchange'    => 'G',
	),

	'G' => array(
		'name'        => 'Regiment',
		'method'      => 'LAND',
		'power'       => '20',
		'max_sectors' => '2',
		'size'        => 'large',
		'exchange'    => false,
	),

	'T' => array(
		'name'        => 'Tank',
		'method'      => 'LAND',
		'power'       => '3',
		'max_sectors' => '3',
		'size'        => 'small',
		'exchange'    => 'H',
	),

	'H' => array(
		'name'        => 'Heavy Tank',
		'method'      => 'LAND',
		'power'       => '30',
		'max_sectors' => '3',
		'size'        => 'large',
		'exchange'    => false,
	),

	'F' => array(
		'name'        => 'Fighter',
		'method'      => 'AIR',
		'power'       => '5',
		'max_sectors' => '5',
		'size'        => 'small',
		'exchange'    => 'B',
	),

	'B' => array(
		'name'        => 'Bomber',
		'method'      => 'AIR',
		'power'       => '25',
		'max_sectors' => '5',
		'size'        => 'large',
		'exchange'    => false,
	),

	'D' => array(
		'name'        => 'Destroyer',
		'method'      => 'SEA',
		'power'       => '10',
		'max_sectors' => '1',
		'size'        => 'small',
		'exchange'    => 'C',
	),

	'C' => array(
		'name'        => 'Cruiser',
		'method'      => 'SEA',
		'power'       => '50',
		'max_sectors' => '1',
		'size'        => 'large',
		'exchange'    => false,
	),

	'M' => array(
		'name'        => 'Megamissle',
		'method'      => 'MEGA', // the megamissle can go _anywhere_
		'power'       => '0',    // the megamissle has no defensive power
		'max_sectors' => '10',   // the megamissle can go _anywhere_ (max moves to get anywhere = 8)
		'size'        => 'large',
		'exchange'    => false,  // the megamissle cannot be traded for anything else
	),

	'P' => array(
		'name'        => 'Power Unit',
		'power'       => '1',
		'max_sectors' => '0',    // the power unit cannot go anywhere (stays in reserve)
		'exchange'    => true,   // the power unit can be traded for anything
	),

	'V' => array(
		'name'        => 'Flag',
		'power'       => '0',    // the flag has no defensive power
		'max_sectors' => '0',    // the flag cannot go anywhere (stays in headquarters)
		'exchange'    => false,  // the flag cannot be traded for anything
	),
);


$COLORS = array(
	'Y' => 'Yellow' ,
	'K' => 'Black' ,
	'R' => 'Red' ,
	'A' => 'White'
);

?>